FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy your HTML files
COPY . .

# Copy custom Nginx configuration
COPY default.conf /etc/nginx/conf.d/

EXPOSE 9080

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
