# Use Python 3.9 as the base image
FROM python:3.9

# Copy the Python script into the container
COPY app.py /app/

# Set the working directory
WORKDIR /app

# Run the script when the container starts
CMD ["python", "app.py"]
